import bpy
import importlib
from pathlib import Path

from src.blender_ui.data import state
from src.blender_ui.utils.file_generator import create_and_load_py_file
import src.code_generator.generated_node as generated_node

# this button operator will generate nodes based on the llm response.
# It will create a new text block in the text editor with the generated code.
# It will also save the file to the hard drive for persistence.
# The generated code will be in the form of a function called generated_material()
# which can be called to create the nodes in the shader editor.
# The mesh object selected in the placeholder property will be used to assign the material to.
# The code generation logic will be handled by the LLM and is not part of this operator.
# The operator just handles the file creation and loading.
# The LLM response is expected to be valid python code that defines the function.
# The operator will report an error if no mesh object is selected.
# TODO: The button needs to be set inactive if state.llm_result is None.

class ButtonOperator(bpy.types.Operator):
    """Tooltip"""
    bl_idname = "object.node_generator_button"
    bl_label = "Panel Node Generator"
    
    # The py file which will hold all the generated shader nodes from the llm.
    file_to_create = Path(__file__).resolve().parents[2] / "code_generator" / "generated_node.py"
    text_block_name = "generated_node.py" # text block name saved in the Text Editor inside Blender.
    
    def execute(self, context):
        mesh_object = context.scene.my_mesh_placeholder
        
        if not mesh_object or mesh_object.type != 'MESH':
            self.report({'ERROR'}, "Please select a mesh object using the dropper.")
            return {'CANCELLED'}
    
        # Example usage: apply a red material to the active object
        #plane = bpy.context.active_object
        #assign_principled_material(mesh_object, color=(1, 0, 0, 1), name="RedMaterial") # This part would be generated by the SLM.
        print("llm response saved: ", state.last_llm_response)
        #if state.last_llm_response is not None:
        llm_response = state.last_llm_response.strip("`").replace("python\n", "", 1)
        create_and_load_py_file(ButtonOperator.file_to_create, ButtonOperator.text_block_name, content = llm_response )

        # Call the generated function to create nodes and assign material.
        importlib.reload(generated_node)
        generated_node.generated_material()

        return {'FINISHED'}