import bpy
from src.blender_ui.utils.file_generator import create_and_load_py_file
from src.examples.material import assign_principled_material

class ButtonOperator(bpy.types.Operator):
    """Tooltip"""
    bl_idname = "object.node_generator_button"
    bl_label = "Panel Node Generator"
    
    # The py file which will hold all the generated shader nodes from the llm.
    file_to_create = "generated_node.py" # File name saved on the Hard drive
    text_block_name = "generated_node.py" # text block name saved in the Text Editor inside Blender.
    
    def execute(self, context):
        mesh_object = context.scene.my_mesh_placeholder
        
        if not mesh_object or mesh_object.type != 'MESH':
            self.report({'ERROR'}, "Please select a mesh object using the dropper.")
            return {'CANCELLED'}
    
        # Example usage: apply a red material to the active object
        #plane = bpy.context.active_object
        assign_principled_material(mesh_object, color=(1, 0, 0, 1), name="RedMaterial") # This part would be generated by the SLM.
        create_and_load_py_file(ButtonOperator.file_to_create, ButtonOperator.text_block_name, content = "# this is the generated content from SLM") # TODO: change this

        return {'FINISHED'}