# To make this add-on installable, create an extension with it:
# https://docs.blender.org/manual/en/latest/advanced/extensions/getting_started.html

import textwrap
import os, sys

import bpy
from bpy.props import StringProperty
from bpy.utils import register_class, unregister_class
from bpy.types import Operator, Panel, PropertyGroup

# add the location of the python files into the system path
dir = os.path.dirname(bpy.data.filepath)
if not dir in sys.path:
    sys.path.append(dir )

import node_copilot.material
import node_copilot.file_generator

# this next part forces a reload in case you edit the source after you first start the blender session
import imp
imp.reload(node_copilot.material)
imp.reload(node_copilot.file_generator)

# this is optional and allows you to call the functions without specifying the package name
from node_copilot.material import assign_principled_material
from node_copilot.file_generator import create_and_load_py_file

class ChatboxData(PropertyGroup):
    chat_history: StringProperty(name="Chat History", default="")
    chat_input: StringProperty(name="Chat Input", default="")

class ButtonOperator(bpy.types.Operator):
    """Tooltip"""
    bl_idname = "object.node_generator_button"
    bl_label = "Panel Node Generator"
    
    # The py file which will hold all the generated shader nodes from the llm.
    file_to_create = "generated_node.py" # File name saved on the Hard drive
    text_block_name = "generated_node.py" # text block name saved in the Text Editor inside Blender.
    
    def execute(self, context):
        mesh_object = context.scene.my_mesh_placeholder
        
        if not mesh_object or mesh_object.type != 'MESH':
            self.report({'ERROR'}, "Please select a mesh object using the dropper.")
            return {'CANCELLED'}
    
        # Example usage: apply a red material to the active object
        #plane = bpy.context.active_object
        assign_principled_material(mesh_object, color=(1, 0, 0, 1), name="RedMaterial") # This part would be generated by the SLM.
        create_and_load_py_file(ButtonOperator.file_to_create, ButtonOperator.text_block_name, content = "# this is the generated content from SLM")

        return {'FINISHED'}
 
class ChatOperator(bpy.types.Operator):
    bl_idname = "object.chat_operator"
    bl_label = "Send Message"
    
    def execute(self, context):
        scene = context.scene
        if scene.chat_input:
            # Append the message to the history with a newline
            scene.chat_history += f"User: {scene.chat_input}\n"
            # Clear the input box
            scene.chat_input = ""
            # Refresh the UI to show the new message
            #bpy.ops.wm.redraw_all()
            
        return {'FINISHED'}

# --- Helper function for multiline text ---
def _label_multiline(context, text, parent):
    if not text:
        return
    # This is a good approximation, but a proper solution would use a text editor template
    chars = int(context.region.width / 7) if context.region else 80
    wrapper = textwrap.TextWrapper(width=chars)
    text_lines = wrapper.wrap(text=text)
    for text_line in text_lines:
        parent.label(text=text_line)

class NodeCoPilotPanel(bpy.types.Panel):
    """Creates a Panel in the Object properties window"""
    bl_label = "Node CoPilot Panel"
    bl_idname = "OBJECT_PT_node_copilot"
    bl_space_type = 'VIEW_3D'
    bl_region_type = 'UI'
    bl_category = "Node CoPilot" # addon name on the panel itself.

    def draw(self, context):
        layout = self.layout

        obj = context.object
        
        layout = self.layout
        # Draw the new mesh placeholder property
        layout.prop(context.scene, "my_mesh_placeholder", text="Mesh Object")
        
        # --- Start of Chat Box UI ---
        
        # A horizontal line to separate the sections
        layout.separator()
        layout.label(text="Chat with Copilot:")
        
        # Conversation History
        box = layout.box()
        box.prop(context.scene, "chat_history", text="", emboss=False)
        
        # Input Field and Send Button
        row = layout.row(align=True)
        row.prop(context.scene, "chat_input", text="", icon='DOT')
        row.operator("object.chat_operator", text="Send", icon='RIGHTARROW')
        
        # --- End of Chat Box UI ---
        
        #layout.prop(context.scene, "copilot_text", text="")
        layout.operator(ButtonOperator.bl_idname, text="Generate Nodes", icon='WORLD_DATA')

_classes = [ButtonOperator, NodeCoPilotPanel, ChatOperator]

def register():
    # 1. Define a StringProperty with the 'AREA' subtype to create a multi-line text box.
    
    bpy.types.Scene.my_mesh_placeholder = bpy.props.PointerProperty(
        type=bpy.types.Object,
        name="Mesh Placeholder",
        poll=lambda self, obj: obj.type == 'MESH'
    )
    
    bpy.types.Scene.chat_history = bpy.props.StringProperty(
        name="Chat History",
        default="",
        #subtype='AREA'  # This makes it a multi-line text box
    )
    
    bpy.types.Scene.chat_input = bpy.props.StringProperty(
        name="Chat Input",
        default=""
    )
        
    ## This property is registered on the global Blender Scene, so its value persists.
    #bpy.types.Scene.copilot_text = bpy.props.StringProperty(
    #    name="Your Text",
    #    description="Type Here",
    #    default=""
    #)
    
    # Register the PropertyGroup and the PointerProperty to it
    bpy.utils.register_class(ChatboxData)
    bpy.types.Scene.chatbox_data = bpy.props.PointerProperty(type=ChatboxData)
    
    for cls in _classes:
        register_class(cls)


def unregister():
    for cls in _classes:
        unregister_class(cls)
    #bpy.utils.unregister_class(ChatboxData)


if __name__ == '__main__':
    register()