# To make this add-on installable, create an extension with it:
# https://docs.blender.org/manual/en/latest/advanced/extensions/getting_started.html

import threading
import textwrap
import os, sys

import bpy
from bpy.props import StringProperty, CollectionProperty
from bpy.utils import register_class, unregister_class
from bpy.types import Operator, Panel, PropertyGroup

# add the location of the python files into the system path
dir = os.path.dirname(bpy.data.filepath)
if not dir in sys.path:
    sys.path.append(dir )

import node_copilot.src.examples.material
import node_copilot.src.blender_ui.file_generator
import node_copilot.src.open_ai.openai_call
import node_copilot.src.data_utils.load_json

# this next part forces a reload in case you edit the source after you first start the blender session
import imp
imp.reload(node_copilot.src.examples.material)
imp.reload(node_copilot.src.blender_ui.file_generator)
imp.reload(node_copilot.src.open_ai.openai_call)
imp.reload(node_copilot.src.data_utils.load_json)

# this is optional and allows you to call the functions without specifying the package name
from node_copilot.src.examples.material import assign_principled_material
from node_copilot.src.blender_ui.file_generator import create_and_load_py_file
from node_copilot.src.open_ai.openai_call import OpenAICaller
from node_copilot.src.data_utils.load_json import load_system_prompt

llm_result = None

def check_llm_result(scene):
    global llm_result
    if llm_result is not None:
        # Safe: updating Blender or UI
        # Add LLM Response
        llm_msg = scene.chat_history.add()
        llm_msg.content = llm_result #"""Hello! 😊 
                            #How can I help you today?""" # replce with LLm invoke function here.
        llm_msg.sender = "LLM"
        #print("LLM reply:", llm_result)
        
        # Reset the variable
        llm_result = None
        
        # Refreshes the panel to show the response from LLM.
        for window in bpy.context.window_manager.windows:
            for area in window.screen.areas:
                if area.type == 'VIEW_3D':
                    area.tag_redraw()
        return None  # Stop the timer
    return 0.2  # Check again in 0.2 seconds

class ChatMessage(PropertyGroup):
    content: StringProperty(name="Chat", default="")
    sender: StringProperty(name="sender", default="USER") # To track if it's "USER" or "LLM"

class ChatboxData(PropertyGroup):
    chat_history: CollectionProperty(type=ChatMessage)
    chat_input: StringProperty(name="Chat Input", default="")

class ButtonOperator(bpy.types.Operator):
    """Tooltip"""
    bl_idname = "object.node_generator_button"
    bl_label = "Panel Node Generator"
    
    # The py file which will hold all the generated shader nodes from the llm.
    file_to_create = "generated_node.py" # File name saved on the Hard drive
    text_block_name = "generated_node.py" # text block name saved in the Text Editor inside Blender.
    
    def execute(self, context):
        mesh_object = context.scene.my_mesh_placeholder
        
        if not mesh_object or mesh_object.type != 'MESH':
            self.report({'ERROR'}, "Please select a mesh object using the dropper.")
            return {'CANCELLED'}
    
        # Example usage: apply a red material to the active object
        #plane = bpy.context.active_object
        assign_principled_material(mesh_object, color=(1, 0, 0, 1), name="RedMaterial") # This part would be generated by the SLM.
        create_and_load_py_file(ButtonOperator.file_to_create, ButtonOperator.text_block_name, content = "# this is the generated content from SLM")

        return {'FINISHED'}
 
class ChatOperator(bpy.types.Operator):
    bl_idname = "object.chat_operator"
    bl_label = "Send Message"
    
    def execute(self, context):
        scene = context.scene
        if scene.chat_input:
            # Append the message to the history with a newline
            #scene.chat_history += f"User: {scene.chat_input}\n"
            new_msg = scene.chat_history.add()
            new_msg.content = scene.chat_input # Take what's in the input field
            new_msg.sender = "USER"
            
            thread = threading.Thread(target=worker, args=(new_msg.content,))
            thread.start()

            # Start polling
            bpy.app.timers.register(lambda: check_llm_result(scene))

            # Clear the input box
            scene.chat_input = ""
            
        return {'FINISHED'}

def draw_multiline_text(layout, text, width=40):
    # This splits the long string into a list of shorter lines
    lines = textwrap.wrap(text, width=width)
    
    col = layout.column(align=True)
    for line in lines:
        col.label(text=line)

class NodeCoPilotPanel(bpy.types.Panel):
    """Creates a Panel in the Object properties window"""
    bl_label = "Node CoPilot Panel"
    bl_idname = "OBJECT_PT_node_copilot"
    bl_space_type = 'VIEW_3D'
    bl_region_type = 'UI'
    bl_category = "Node CoPilot" # addon name on the panel itself.

    def draw(self, context):
        layout = self.layout

        obj = context.object
        
        layout = self.layout
        # Draw the new mesh placeholder property
        layout.prop(context.scene, "my_mesh_placeholder", text="Mesh Object")
        
        # Start of Chat Box UI

        # A horizontal line to separate the sections
        layout.separator()
        layout.label(text="Chat with Blender Node Copilot:")
        
        # Conversation History
        box = layout.box()
        #box.prop(context.scene, "chat_history", text="", emboss=False)
        
        # To make it look like a square, we create a column 
        # inside the box and scale its height.
        col = box.column(align=True)
        
        # Adding a label or empty space keeps the box from collapsing
        col.label(text="")
    
        # Create a box for eveyr new message
        for msg in context.scene.chat_history:
            # Create a row to align left (LLM) /right (USER)
            row = col.row()
            if msg.sender == "USER":
                row.separator(factor=2)
            
                # Create the individual bubble
                inner_box = row.box()
                inner_col = inner_box.column(align=True)
                inner_col.scale_y = 1
    
                # Draw the text using your function
                draw_multiline_text(inner_col, msg.content, width=30)

            else:
                # Create the individual bubble
                inner_box = row.box()
                inner_col = inner_box.column(align=True)
                inner_col.scale_y = 1
                
                # Draw the text using your function
                draw_multiline_text(inner_col, msg.content, width=30)
                row.separator()
        # ---------------------------- # 

        # Input Field and Send Button
        row = layout.row(align=True)
        row.prop(context.scene, "chat_input", text="")
        row.operator("object.chat_operator", text="", icon='RIGHTARROW')
        
        # End of Chat Box UI
        
        # Add the Chat clear button
        layout.operator("chat.clear_history", text="Clear Chat History", icon='TRASH')
        
        layout.operator(ButtonOperator.bl_idname, text="Generate Nodes (Python Code)", icon='WORLD_DATA')

class CHAT_OT_clear_history(bpy.types.Operator):
    bl_idname = "chat.clear_history"
    bl_label = "Clear Chat"
    bl_description = "Delete all messages in the chat history"
    
    def execute(self, context):
        # This empties the entire collection at once
        context.scene.chat_history.clear()
        
        # Optional: Reset the input field too
        context.scene.chat_input = ""
        
        return {'FINISHED'}

_classes = [ChatMessage, ButtonOperator, NodeCoPilotPanel, ChatOperator, CHAT_OT_clear_history]

def register():
    
    for cls in _classes:
        register_class(cls)
    # 1. Define a StringProperty with the 'AREA' subtype to create a multi-line text box.
    
    bpy.types.Scene.my_mesh_placeholder = bpy.props.PointerProperty(
        type=bpy.types.Object,
        name="Mesh Placeholder",
        poll=lambda self, obj: obj.type == 'MESH'
    )
    
    bpy.types.Scene.chat_input = bpy.props.StringProperty(
        name="Chat Input",
        default=""
    )
    
    bpy.types.Scene.chat_history = bpy.props.CollectionProperty(type=ChatMessage)
    
    # Register the PropertyGroup and the PointerProperty to it
    bpy.utils.register_class(ChatboxData)
    bpy.types.Scene.chatbox_data = bpy.props.PointerProperty(type=ChatboxData)
    
def unregister():
    for cls in _classes:
        unregister_class(cls)

def worker(user_messages):
    global llm_result
    caller = OpenAICaller()
    system_prompt = load_system_prompt()
    llm_result = caller.send(system_prompt, user_message=user_messages)
    print(llm_result) # print the response in the Blender console for debugging

if __name__ == '__main__':
    register()