Process:
  SFT:
    Train: True # If set to true, it starts train, esle inference.
  RewardModel:
    FineTune: False

Model:
  model_name: "Qwen/Qwen2.5-Coder-0.5B"

Data:
  dataset_file: "" # file
  dataset_path: "" # root

Train:
  max_length: 2000
  num_train_epochs: 10
  learning_rate: 3e-4

Logging:
  logging_steps: 10
  logging_dir: './logs'
  output_dir: './phi3-mini-yoda-adapter'
  report_to: 'none'

